name: Build App Inventor Extension

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build Extension with AIX-Action
      uses: pavi2410/AIX-Action@main
      with:
        source-dir: '.'

    - name: Locate and Copy AIX
      run: |
        find . -name "*.aix" -exec cp {} . \;
        ls -la

    - name: Upload AIX Artifact
      uses: actions/upload-artifact@v4
      with:
        name: CameraXExtension-aix
        path: ./*.aix
